# FROM alpine:3.18
FROM byuoitav/amd64-alpine


ARG NAME
ENV name=${NAME}

COPY ${name}-arm ${name}-arm
COPY version.txt version.txt

# add any required files/folders here

ENTRYPOINT ["/hid-reader-microservice-arm"]